"use client"

import {
  Star,
  GraduationCap,
  Briefcase,
  User,
  Heart,
  ChartLine,
  Bot,
  Sun,
  AtSign,
  Home,
  HeartPulse,
  Sparkles,
  Search,
  Plus,
  Mic,
  MicOff,
  Send,
  X,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Zap,
  ListChecks,
  Users,
  Trophy,
  Info,
  Lightbulb,
  Flame,
  CalendarClock,
  CalendarPlus,
  ArrowUp,
  GripVertical,
  Check,
  CheckCheck,
  Trash2,
  Settings,
  RotateCcw,
  Moon,
  SunMedium,
  ArrowRight,
  MoreHorizontal,
  Pencil,
  GitBranch,
  Link2,
  Lock,
  Table2,
  Download,
  BarChart3,
  Filter,
  Unlink,
  Compass,
  Clock,
  FolderOpen,
  type LucideIcon,
} from "lucide-react"

const MAP: Record<string, LucideIcon> = {
  star: Star,
  "graduation-cap": GraduationCap,
  briefcase: Briefcase,
  user: User,
  heart: Heart,
  "chart-line": ChartLine,
  robot: Bot,
  sun: Sun,
  "at-sign": AtSign,
  home: Home,
  "heart-pulse": HeartPulse,
  sparkles: Sparkles,
  search: Search,
  plus: Plus,
  mic: Mic,
  "mic-off": MicOff,
  send: Send,
  x: X,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  zap: Zap,
  "list-checks": ListChecks,
  users: Users,
  trophy: Trophy,
  info: Info,
  lightbulb: Lightbulb,
  flame: Flame,
  "calendar-clock": CalendarClock,
  "calendar-plus": CalendarPlus,
  "arrow-up": ArrowUp,
  "arrow-right": ArrowRight,
  grip: GripVertical,
  check: Check,
  "check-check": CheckCheck,
  trash: Trash2,
  settings: Settings,
  reset: RotateCcw,
  moon: Moon,
  "sun-medium": SunMedium,
  more: MoreHorizontal,
  pencil: Pencil,
  branch: GitBranch,
  chain: Link2,
  unchain: Unlink,
  lock: Lock,
  table: Table2,
  download: Download,
  "bar-chart": BarChart3,
  filter: Filter,
  compass: Compass,
  clock: Clock,
  folder: FolderOpen,
}

export function Icon({
  name,
  className,
  size = 16,
}: {
  name: string
  className?: string
  size?: number
}) {
  const C = MAP[name] ?? Star
  return <C className={className} size={size} strokeWidth={1.8} />
}
